---
version: "3.7"

networks:
  glpi-backend:

volumes:
  glpi-db:
    driver_opts:
      type: none
      device: ./glpi-db
      o: bind
  glpi-root:
  glpi-files:
    driver_opts:
      type: none
      device: ./glpi-files
      o: bind
  glpi-etc:
    driver_opts:
      type: none
      device: ./glpi-etc
      o: bind
  glpi-phpmyadmin:

services:
  # Database Container
  mariadb:
    image: mariadb:10.5
    container_name: glpi-db
    networks:
      - glpi-backend
    volumes:
      - glpi-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "glpi"
      MYSQL_USER: "glpi"
      MYSQL_PASSWORD: "glpi"

  # GLPI Container
  glpi:
    image: cbrandel/glpi:9.5.5
    depends_on:
      - mariadb
    container_name: glpi-app
    links:
      - "mariadb:glpi-db"
    networks:
      - glpi-backend
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - glpi-root:/var/www/glpi
      - glpi-files:/var/lib/glpi
      - glpi-etc:/etc/glpi
    environment:
      TZ: "Europe/Berlin"
      MYSQL_DATABASE: "glpi"
      MYSQL_USER: "glpi"
      MYSQL_PASSWORD: "glpi"
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.glpicron.schedule: "@every 2m"
      ofelia.job-exec.glpicron.command: "/usr/local/bin/php /var/www/glpi/front/cron.php"

  # nginx container
  nginx:
    image: nginx:stable-alpine
    depends_on:
      - glpi
      - phpmyadmin
    container_name: glpi-web
    networks:
      - glpi-backend
    ports:
      - 80:80
    volumes:
      - glpi-root:/var/www/glpi
      - glpi-files:/var/lib/glpi
      - glpi-phpmyadmin:/var/www/html/
      - ./templates:/etc/nginx/templates
    environment:
      - NGINX_HOST=glpi.example.com
      - NGINX_PORT=80
      - NGINX_DOCROOT=/var/www/glpi

  # Scheduler
  scheduler:
    image: mcuadros/ofelia:v0.3.4
    depends_on:
      - glpi
    container_name: glpi-sched
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  # Phpmyadmin Container
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5-fpm-alpine
    container_name: glpi-pma
    networks:
      - glpi-backend
    volumes:
      - glpi-phpmyadmin:/var/www/html/
    environment:
      - PMA_ARBITRARY=1
      - PMA_ABSOLUTE_URI=http://pma.example.com